
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Shared-Project/Pipeline-Templates
      ref: refs/heads/main

stages:
  - template: build/python-library.yml@templates
    parameters:
      appName: 'azure-data-toolkit'
      pythonVersion: '3.11'
      artifactVariableGroup: 'GitHubPAT'
      artifactRepoOwner: 'AllakaNarasimha'
      artifactRepoName: 'data-fetcher-artifacts'
      artifactRetentionCount: 5
      azureArtifactFeed: 'Enterprise-Releases'
